<a href="https://colab.research.google.com/github/galahad20/assignment_Data_Cleaning/blob/main/ASSIGNMENT_TEMP_DE14_DAY10_DIMAS_ABIAN_IHSAN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Data Cleaning
by `Dimas Abian Ihsan`

**Dibimbing - Batch 14 | DE**

## Objectives
- Student mampu melakukan cleaning data
- Student mampu mengatasi missing value
- Student mampu mengimport dan mengecek dataframe
- Student mampu melakukan encoding data
- Student mampu mengatasi outier pada sebuah data

## Persiapan

### Import Library

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

%matplotlib inline
print('Libraries Loaded!')

Libraries Loaded!

### Import Dataset employees.csv menggunakan pandas

In [3]:
employee_path = '/content/drive/MyDrive/dibimbing/day10/dataset/employees.csv'
df_employee = pd.read_csv(employee_path)

In [7]:
df_employee.head()

,employee_id,full_name,email,phone,department,position,salary,hire_date,performance_score,status
0,EMP001,Andi Wijaya,andi.wijaya@company.com,81234567890,IT,Software Engineer,15000000,2022-03-15,85,Active
1,EMP002,Budi Santoso,budi.santoso@company,6282345678901,Finance,Accountant,12000000,2021-06-20,78,Active
2,EMP003,Citra Dewi,NaN,83456789012,HR,HR Manager,18000000,2020-01-10,92,Active
3,EMP004,Dian Pratama,dian.pratama@company.com,6284567890123,IT,Data Analyst,14000000,2023-02-28,88,Active
4,EMP005,Eka Putri,eka@company.com,6285678901234,Marketing,Marketing Executive,11000000,2022-08-15,-5,Active

## Pemahaman Dataset

### Tampilkan info dan statistik desriptive

In [8]:
df_employee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   employee_id        31 non-null     object
 1   full_name          31 non-null     object
 2   email              26 non-null     object
 3   phone              31 non-null     int64
 4   department         31 non-null     object
 5   position           31 non-null     object
 6   salary             31 non-null     int64
 7   hire_date          31 non-null     object
 8   performance_score  31 non-null     int64
 9   status             31 non-null     object
dtypes: int64(3), object(7)
memory usage: 2.6+ KB

Deksripsi Kolom
- employee-id : tanda pengenal yang dimiliki setiap employee. Sifatnya unqiue
- full_name : nama lengkap employee
- email : email milik employee
- phone : nomor telpon aktif karyawan yang dapat dihubungi
- department : Unit kerja atau departemen tempat karyawan bernaung (misal: IT, HR, Finance).
- position : jabatan employee
- salary : gaji employee
- hire_date : Tanggal resmi karyawan mulai bekerja di perusahaan
- performance_score : Nilai evaluasi kinerja karyawan yang biasanya diberikan dalam skala numerik atau kategori.
- status: status keaktifan karyawan

In [9]:
df_employee.describe()

              phone        salary  performance_score
count  3.100000e+01  3.100000e+01          31.000000
mean   3.283022e+12  1.312903e+07          80.580645
std    3.149403e+12  2.918241e+06          16.863717
min    8.111122e+10  8.500000e+06          -5.000000
25%    8.238900e+10  1.100000e+07          78.500000
50%    6.280123e+12  1.300000e+07          83.000000
75%    6.282340e+12  1.500000e+07          87.500000
max    6.289012e+12  2.000000e+07          95.000000